### ISSUE TITLE
indagare il link

### ISSUE THREAD

**Issue by Koldar** [STB1019/SkullOfSummer#24]
https://www.thegeekstuff.com/2012/04/create-proc-files/

Cercare di capire come creare un file in "/proc" in modo tale che il progetto della tastiera possa buttare su suddetto file in "/proc" le statistiche della tastiera stessa

**Comment by lorenzonodari** [comment]
The /proc folder is a pseudo-fs created by the Linux Kernel in order to create an interface between the kernel status and the user-space programs. You can see that, due to this reason, it is by default a read-only folder for everyone, root included. It contains only __virtual__ files that contain informations about devices, statistics, etc.. Creating a new "file" in this folder is surely possible, but, as far as i know, only at kernel-level. This means one should create a kernel module in order to handle this kind of need. Thus, i think this task would be a little too hard for the purposes of the SoS, and a little out of scope.

**Comment by Koldar** [comment]
Yeah, totally a won't do :) thanks!
